AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-app-jawsdays
Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: True
    OpenApiVersion: 3.0.2

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:33
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get